name: Daily 5 AM HK Time Job

on:
  schedule:
    # Runs at 5 AM every day in Hong Kong time (UTC+8)
    # 5 AM HK = 9 PM previous day UTC
    - cron: '0 21 * * *'
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  execute-daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: |
          pnpm install
          
      - name: Run CTB & KMB data collection
        run: |
          pnpm collect-data
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4