name: Daily 5 AM HK Time Job

on:
  schedule:
    # Runs at 5 AM every day in Hong Kong time (UTC+8)
    # 5 AM HK = 9 PM previous day UTC
    - cron: '0 21 * * *'
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  execute-daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      - name: Install dependencies
        run: |
          pnpm install
          
      - name: Run CTB & KMB data collection
        run: |
          echo "Starting data collection at $(date)"
          pnpm collect-data
          echo "Data collection completed at $(date)"
          
      - name: Verify data collection
        run: |
          echo "Verifying collected data..."
          if [ -d "ctb/stops" ]; then
            echo "CTB stops count: $(find ctb/stops/ -name "*.json" 2>/dev/null | wc -l)"
          fi
          if [ -d "kmb/stops" ]; then
            echo "KMB stops count: $(find kmb/stops/ -name "*.json" 2>/dev/null | wc -l)"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp -r ctb/ deploy/ 2>/dev/null || echo "CTB directory not found"
          cp -r kmb/ deploy/ 2>/dev/null || echo "KMB directory not found"
          cp index.html deploy/ 2>/dev/null || echo "index.html not found"
          cp README.md deploy/ 2>/dev/null || echo "README.md not found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4